run:
    cases: [cylinder]

defaults:
    mesh:
        type: structured
        dim: 2
        cells:
            x: 100
            y: 3
            z: 1
        domain:
            x: 1.0
            y: 1.0
            z: 1.0

    physics:
        eos: ideal_gas
        parameters:
            gamma: 1.4
            reactant_mass_fraction: 1.0

    numerics:
        method: godunov-kolgan
        parameters:
            time_integrator: euler
            reconstruction: p1
            riemann_solver: exact
            cfl: 0.5
            global_limiter: false
            viscosity: false
            diffusion: false

    boundary_conditions:
        x_min: outlet
        x_max: outlet
        y_min: outlet
        y_max: outlet
        z_min: reflective
        z_max: reflective

    immersed_boundaries:
        enabled: true
        objects: []

    parallel:
        mpi: true

    stopping:
        t_end: 0.25
        max_steps: 0

    logging:
        every_steps: 10
        every_time: 0.0

    output:
        format: vtk
        directory: ../result
        every_steps: 1
        every_time: 0.0

cases:
    cylinder:
        mesh:
            domain:
                x: 10.0
                y: 1.0
                z: 1.0
            dim: 2
            cells:
                x: 2000
                y: 200
                z: 1
        immersed_boundaries:
            enabled: true
            objects:
                - type: circle
                  cx: 3
                  cy: 0.5
                  radius: 0.1
        initial_condition:
            type: structured_regions
            interfaces:
                x: [ ]
                y: [ ]
                z: [ ]
            rho: [ 1.0 ]
            u: [ 1.0 ]
            v: [ 0.0 ]
            w: [ 0.0 ]
            p: [ 1.0 ]
        stopping:
            t_end: 2
    sod1:
        initial_condition:
            type: structured_regions
            interfaces:
                x: [0.5]
                y: []
                z: []
            rho: [1.0, 0.125]
            u:   [0.0, 0.0]
            v:   [0.0, 0.0]
            w:   [0.0, 0.0]
            p:   [1.0, 0.1]
        stopping:
            t_end: 0.2

    sod1_2d:
        mesh:
            dim: 2
            cells:
                x: 400
                y: 400
                z: 1
        initial_condition:
            type: structured_regions
            interfaces:
                x: [0.5]
                y: []
                z: []
            rho: [1.0, 0.125]
            u:   [0.0, 0.0]
            v:   [0.0, 0.0]
            w:   [0.0, 0.0]
            p:   [1.0, 0.1]
        boundary_conditions:
            x_min: reflective
            x_max: reflective
            y_min: reflective
            y_max: reflective
        output:
            every_steps: 20
        stopping:
            t_end: 0.25

    sod1_2d_y:
        mesh:
            dim: 2
            cells:
                x: 200
                y: 200
                z: 1
        initial_condition:
            type: structured_regions
            interfaces:
                x: []
                y: [0.5]
                z: []
            rho:
                - 1.0
                - 0.125
            u:
                - 0.0
                - 0.0
            v:
                - 0.0
                - 0.0
            w:
                - 0.0
                - 0.0
            p:
                - 1.0
                - 0.1
        output:
            every_steps: 100
        stopping:
            t_end: 0.25

    lax_liu_3:
        mesh:
            dim: 2
            cells:
                x: 400
                y: 400
                z: 1
            domain:
                x: 1.0
                y: 1.0
                z: 1.0
        physics:
            eos: ideal_gas
            parameters:
                gamma: 1.4
        numerics:
            parameters:
                cfl: 0.4
        boundary_conditions:
            x_min: reflective
            x_max: reflective
            y_min: reflective
            y_max: reflective
        initial_condition:
            type: structured_regions
            interfaces:
                x: [0.5]
                y: [0.5]
                z: []
            rho:
                - [0.138, 0.5323]
                - [0.5323, 1.5]
            u:
                - [1.206, 1.206]
                - [0.0,   0.0]
            v:
                - [1.206, 0.0]
                - [1.206, 0.0]
            w:
                - [0.0, 0.0]
                - [0.0, 0.0]
            p:
                - [0.029, 0.3]
                - [0.3,   1.5]
        output:
            every_steps: 20
        stopping:
            t_end: 1.5

    lax_liu_12:
        mesh:
            dim: 2
            cells:
                x: 400
                y: 400
                z: 1
        physics:
            eos: ideal_gas
            parameters:
                gamma: 1.4
        numerics:
            parameters:
                cfl: 0.4
        boundary_conditions:
            x_min: reflective
            x_max: reflective
            y_min: reflective
            y_max: reflective
        initial_condition:
            type: structured_regions
            interfaces:
                x: [0.5]
                y: [0.5]
                z: []
            rho:
                - [1.0, 0.8]
                - [1.0, 0.8]
            u:
                - [0.0, 0.0]
                - [0.7276, 0.0]
            v:
                - [0.7276, 0.0]
                - [0.0,    0.0]
            w:
                - [0.0, 0.0]
                - [0.0, 0.0]
            p:
                - [1.0, 1.0]
                - [1.0, 1.0]
        output:
            every_steps: 200
        stopping:
            t_end: 0.25

    octant_test:
        mesh:
            dim: 3
            cells:
                x: 100
                y: 100
                z: 100
        initial_condition:
            type: structured_regions
            interfaces:
                x: [0.5]
                y: [0.5]
                z: [0.5]
            rho:
                -
                    - [1.0, 0.8]
                    - [0.7, 0.6]
                -
                    - [0.5, 0.4]
                    - [0.3, 0.2]
            u:
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
            v:
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
            w:
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
                -
                    - [0.0, 0.0]
                    - [0.0, 0.0]
            p:
                -
                    - [1.0, 1.0]
                    - [1.0, 1.0]
                -
                    - [1.0, 1.0]
                    - [1.0, 1.0]

#    gmsh_case_template:
#        mesh:
#            type: unstructured
#            source:
#                format: geo
#                file: meshes/example.geo
#                generator: gmsh
#        physics:
#            eos: ideal_gas
#            parameters:
#                gamma: 1.4
#        numerics:
#            method: godunov
#            parameters:
#                time_integrator: euler
#                reconstruction: p0
#                riemann_solver: hllc
#                cfl: 0.4
#        boundary_conditions:
#            default: outlet
#        initial_condition:
#            type: region_markers
#            regions:
#                - marker: fluid_1
#                  rho: 1.0
#                  u: 0.0
#                  v: 0.0
#                  w: 0.0
#                  p: 1.0
#                - marker: fluid_2
#                  rho: 0.125
#                  u: 0.0
#                  v: 0.0
#                  w: 0.0
#                  p: 0.1